### PR TITLE
Group permissions by subject

### PR DESCRIPTION
**Pull request by amoeba**
Addresses https://github.com/ropensci/datapack/issues/53. I find unique subjects, adding an <allow> block for each, and for each subject, I find the unique set of their permissions and add <permission> blocks for each as sibling node to the respective <subject> element.

Edit: Spelling.

### CODE REVIEW

**Comment by mbjones** [comment]
This looks good.  Is there a need for any extended tests to make sure that this new layout is working correctly?

**Comment by amoeba** [comment]
Added a pretty basic test.

**Comment by mbjones** [comment]
@gothub indicated in the 1.0.1 release notes that a similar feature of grouping subjects in access policies was included. Is this pull request #54 different than what was already released?  If so, can this PR be closed, or should it instead be fixed up and merged? Thoughts, @amoeba ?

**Comment by amoeba** [comment]
Looks like this is already in and this PR can be closed without merge. See https://github.com/ropensci/datapack/blob/master/R/SystemMetadata.R#L350

**Comment by gothub** [comment]
@amoeba apologies Bryce, I didn't see your PR way back then - I've made checking for
PRs part of my workflow since then.

**Comment by amoeba** [comment]
Np at all. It was a couple lines of code.

**Pull request closed without merging**
